### ISSUE TITLE
Z_BUF_ERROR

### ISSUE THREAD

**Issue by lucasgonze** [pillsilly/recursive-unzipper#3]
Thanks for this handy thing. Thought you'd want to know that I'm getting a fatal error on an archive:

```
$ recursive-unzipper -f 1591239073.zip
{ file: 'UC-One_Collaborate_WIN-3.9.11-1591239073.zip' }
[15:43:50.074] INFO (recursive-unzipper): Extracting zip [UC-One_Collaborate_WIN-3.9.11-1591239073.zip]
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
Emitted 'error' event on DuplexWrapper instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at errorOrDestroy (node:internal/streams/destroy:220:7)
    at DuplexWrapper.onerror (node:internal/streams/readable:771:9)
    at DuplexWrapper.emit (node:events:527:28)
    at Parse.<anonymous> (/Users/lucasgonze/.nvm/versions/node/v16.15.0/lib/node_modules/recursive-unzipper/node_modules/duplexer2/index.js:45:12)
    at Parse.emit (node:events:527:28)
    at InflateRaw.<anonymous> (/Users/lucasgonze/.nvm/versions/node/v16.15.0/lib/node_modules/recursive-unzipper/node_modules/unzipper/lib/parse.js:188:46)
    at InflateRaw.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}

```

It's totally possible there is a corrupt sub-archive in this big bundle. Ideally the program would report it and move on to the next unzippable thing.

The archive file I'm using is proprietary and can't be shared. Sorry. I realize that makes this report not so useful.

**Comment by pillsilly** [comment]
> Thanks for this handy thing. Thought you'd want to know that I'm getting a fatal error on an archive:
> 
> ```
> $ recursive-unzipper -f 1591239073.zip
> { file: 'UC-One_Collaborate_WIN-3.9.11-1591239073.zip' }
> [15:43:50.074] INFO (recursive-unzipper): Extracting zip [UC-One_Collaborate_WIN-3.9.11-1591239073.zip]
> node:events:505
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: unexpected end of file
>     at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
> Emitted 'error' event on DuplexWrapper instance at:
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at errorOrDestroy (node:internal/streams/destroy:220:7)
>     at DuplexWrapper.onerror (node:internal/streams/readable:771:9)
>     at DuplexWrapper.emit (node:events:527:28)
>     at Parse.<anonymous> (/Users/lucasgonze/.nvm/versions/node/v16.15.0/lib/node_modules/recursive-unzipper/node_modules/duplexer2/index.js:45:12)
>     at Parse.emit (node:events:527:28)
>     at InflateRaw.<anonymous> (/Users/lucasgonze/.nvm/versions/node/v16.15.0/lib/node_modules/recursive-unzipper/node_modules/unzipper/lib/parse.js:188:46)
>     at InflateRaw.emit (node:events:527:28)
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   errno: -5,
>   code: 'Z_BUF_ERROR'
> }
> ```
> 
> It's totally possible there is a corrupt sub-archive in this big bundle. Ideally the program would report it and move on to the next unzippable thing.
> 
> The archive file I'm using is proprietary and can't be shared. Sorry. I realize that makes this report not so useful.

Hi and thanks for the reporting,
Should I understand that you're asking an error fallback(default as continue to the next one file) mechanism ?

**Comment by lucasgonze** [comment]
>  Should I understand that you're asking an error fallback(default as continue to the next one file) mechanism ?

Yes, that's right. I have a big tarball of tarballs that contains one deeply nested corrupt file.

I will try to make a shareable file to reproduce the error.

**Comment by pillsilly** [comment]
> > Should I understand that you're asking an error fallback(default as continue to the next one file) mechanism ?
> 
> Yes, that's right. I have a big tarball of tarballs that contains one deeply nested corrupt file.
> 
> I will try to make a shareable file to reproduce the error.

Sample file could be not needed if you're sure that the ERROR was caused by the corruption,
-- 🙂I was thinking that there could be caused by algorithm not supported by the lib I used.

**Comment by pillsilly** [comment]
I guess the fail-safe could be easily done, 
current idea in mind is that to make it configurable,
(say if someone gives the option like `--bail=true` then the extraction will get aborted once error is met, otherwise it will always try to continue even if certain file fail the extraction attempt)

I will try to implement it in coming days.

**Comment by lucasgonze** [comment]
>  could be caused by algorithm not supported by the lib I used

The problem was definitely in the file. `tar -xf` and the OS X uncompress app also complained.

**Comment by lucasgonze** [comment]
I found the beast. It's qt-everywhere-src-5.12.4-2.tar.xz. It's pretty big - 484M - and GitHub won't accept the extension here, so I have uploaded it to a personal account: grab gonze.com/tmp/qt-everywhere-src-5.12.4-2.tar.xz

The error I'm seeing in the shell is a little different than the above, so the compression problem might be different. However, the error does cause recursive-unzipper to throw an exception and die.

**Comment by pillsilly** [comment]
I've released a beta version of feature `--bail`

feel free to check if it works as expected @lucasgonze 


` npm i recursive-unzipper@0.2.0-beta.0`

**Comment by lucasgonze** [comment]
Something is borked with the package.

```
M1-Air-2086:todo lucasgonze$ npm install -g recursive-unzipper@0.2.0-beta.0

added 113 packages in 8s

28 packages are looking for funding
  run `npm fund` for details

M1-Air-2086:todo lucasgonze$ recursive-unzipper -V
0.1.2
```

And when I actually run it on my tarball I get the same error as before.

**Comment by pillsilly** [comment]
> Grab gonze.com/tmp/qt-everywhere-src-5.12.4-2.tar.xz

I wasn't able to open this link, is it started with `http://` ? Though I've tried both http and https 

If it's possible would you maybe try Google Drive which is able to share to anonymous? @lucasgonze

**Comment by pillsilly** [comment]
> > I wasn't able to open this link, is it started with `http://` ? Though I've tried both http and https
> 
> I removed it a couple days after posting that. It's back now:
> 
> https://gonze.com/tmp/qt-everywhere-src-5.12.4-2.tar.xz

Just downloaded it and you can now remove it, thanks for the sample file.

It turns out the file is actually extractable  -- I use third party xz handler and decompressed successfully.

It seems original problems are two

1. is that the error `RangeError [ERR_OUT_OF_RANGE]:` somehow breaks catch blocks (where I haven't figured out how why that error is special while the left errors are able to be caught).
2. is that the code didn't handle huge xz well in previous version.


I'm trying some new implementation to handle such a huge xz above tar and let you know if it could be overcome 🤞

**Comment by pillsilly** [comment]
I made two sample files(xz above tar but intact)
zipped them with yours into one.

![image](https://user-images.githubusercontent.com/13218151/227994359-ab75d4fa-974f-4abc-98d0-38f88c979ba0.png)

to ensure that 
if the middle one (which is huge, and corrupted inside the tar content) 
goes wrong,
the other two similar files are able to get extracted.

Tested ok, and I will make another PR later soon.
